initQuestRegularContent = function() {
  'use strict';

  initQuestRegularContentTutorial();
  initQuestRegularContentEnergyResearch();
  initQuestRegularContentAlloyResearch();
  initQuestRegularContentScienceResearch();
  initQuestRegularContentCrystallizationResearch();
  initQuestRegularContentDrillResearch();
  initQuestRegularContentIkeaResearch();
  initQuestRegularContentAnimalworldResearch();
  initQuestRegularContentNanotechnologyResearch();
  initQuestRegularContentEngineeringResearch();
  initQuestRegularContentEntertainmentBuilding();
  initQuestRegularContentHouseBuilding();
  initQuestRegularContentMetalBuilding();
  initQuestRegularContentSpaceportBuilding();
  initQuestRegularContentTradingportBuilding();
  initQuestRegularContentPulsecatcherBuilding();
  initQuestRegularContentColosseumBuilding();
  initQuestRegularContentCrystalBuilding();
  initQuestRegularContentBlackmarketBuilding();
  initQuestRegularContentPowerstationBuilding();
  initQuestRegularContentLaboratoryBuilding();
  initQuestRegularContentBarracksBuilding();
  initQuestRegularContentFactoryBuilding();
  initQuestRegularContentAirfieldBuilding();
  initQuestRegularContentShipyardBuilding();
  initQuestRegularContentGatesBuilding();
  initQuestRegularContentDefensecomplexBuilding();
};